PUB_DIR=/home/sebastian/Dropbox/masterarbeit/img/


publish:
	cp ./exp0001_singlepage.pdf $(PUB_DIR)/exp0001_singlepage.pdf
	cp ./exp0002_singlepage.pdf $(PUB_DIR)/exp0002_singlepage.pdf
	cp ./exp0003_singlepage.pdf $(PUB_DIR)/exp0003_singlepage.pdf
	cp ./exp0004_singlepage.pdf $(PUB_DIR)/exp0004_singlepage.pdf
	cp ./exp0005.pdf $(PUB_DIR)/exp0005.pdf
	cp ./exp0006_singlepage.pdf $(PUB_DIR)/exp0006_singlepage.pdf
	cp ./exp0007_singlepage.pdf $(PUB_DIR)/exp0007_singlepage.pdf
	cp ./exp0008_singlepage.pdf $(PUB_DIR)/exp0008_singlepage.pdf
	cp ./exp0013_singlepage.pdf $(PUB_DIR)/exp0013_singlepage.pdf
	cp ./exp0014_singlepage.pdf $(PUB_DIR)/exp0014_singlepage.pdf
	cp ./exp0015_singlepage.pdf $(PUB_DIR)/exp0015_singlepage.pdf
	cp ./exp0022_singlepage.pdf $(PUB_DIR)/exp0022_singlepage.pdf
	cp ./exp0023_singlepage.pdf $(PUB_DIR)/exp0023_singlepage.pdf
	cp ./exp0024_singlepage.pdf $(PUB_DIR)/exp0024_singlepage.pdf
	cp ./exp0025_singlepage.pdf $(PUB_DIR)/exp0025_singlepage.pdf
	cp ./exp0026_singlepage.pdf $(PUB_DIR)/exp0026_singlepage.pdf
	cp ./exp0027_singlepage.pdf $(PUB_DIR)/exp0027_singlepage.pdf
	cp ./exp0028_singlepage.pdf $(PUB_DIR)/exp0028_singlepage.pdf
	cp ./exp0029_singlepage.pdf $(PUB_DIR)/exp0029_singlepage.pdf
