EXECUTABLE = image_warping
# OBJS = build/CUDAWarpingSolver.o build/mLibSource.o build/main.o  build/WarpingSolver.o
# OBJS = build/CeresSolverImageWarping.o build/CUDAWarpingSolver.o build/mLibSource.o build/main.o  build/WarpingSolver.o
OBJS = build/shared/CeresSolverBase.o build/CeresSolverImageWarping.o build/CUDAWarpingSolver.o build/mLibSource.o build/main.o  build/WarpingSolver.o
include ../shared/make_template.inc


